"""Pydantic wire contracts for Difflet's OpenAI-style APIs."""

from difflet.serving.openai.protocol.videos import (
    AudioReference,
    FileImageReference,
    FileVideoReference,
    ImageReference,
    SecondStr,
    SizeStr,
    UrlAudioReference,
    UrlImageReference,
    UrlVideoReference,
    VideoAction,
    VideoData,
    VideoDeleteResponse,
    VideoError,
    VideoGenerationRequest,
    VideoGenerationResponse,
    VideoGenerationStatus,
    VideoListResponse,
    VideoParams,
    VideoReference,
    VideoResponse,
    file_extension,
)

__all__ = [
    "AudioReference",
    "FileImageReference",
    "FileVideoReference",
    "ImageReference",
    "SecondStr",
    "SizeStr",
    "UrlAudioReference",
    "UrlImageReference",
    "UrlVideoReference",
    "VideoAction",
    "VideoData",
    "VideoDeleteResponse",
    "VideoError",
    "VideoGenerationRequest",
    "VideoGenerationResponse",
    "VideoGenerationStatus",
    "VideoListResponse",
    "VideoParams",
    "VideoReference",
    "VideoResponse",
    "file_extension",
]
